# Generated by Django 3.1.5 on 2021-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('NamespaceId', models.IntegerField()),
                ('Key', models.CharField(max_length=128)),
                ('Value', models.TextField()),
                ('Comment', models.CharField(max_length=1024)),
                ('LineNum', models.IntegerField()),
                ('IsDelete', models.BooleanField(default=False)),
                ('DataChange_CreateBy', models.CharField(max_length=32)),
                ('DataChange_CreateTime', models.TimeField()),
                ('DataChange_LastModifiedBy', models.CharField(max_length=32)),
                ('DataChange_LastTime', models.TimeField()),
            ],
        ),
    ]
