# Generated by Django 3.1.5 on 2021-01-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confcheck', '0003_auto_20210113_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='DataChange_CreateBy',
            new_name='DataChange_CreatedBy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='DataChange_CreateTime',
            new_name='DataChange_CreatedTime',
        ),
    ]
