# Generated by Django 3.1.5 on 2021-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confcheck', '0004_auto_20210113_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Comment',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='DataChange_LastModifiedBy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='DataChange_LastTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='IsDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='LineNum',
            field=models.IntegerField(null=True),
        ),
    ]
