# Generated by Django 3.1.5 on 2021-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confcheck', '0005_auto_20210113_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('AppId', models.CharField(max_length=500)),
                ('ClusterName', models.CharField(max_length=500)),
                ('NamespaceName', models.CharField(max_length=500)),
                ('IsDeleted', models.BooleanField(default=False, null=True)),
                ('DataChange_CreatedBy', models.CharField(max_length=32)),
                ('DataChange_CreatedTime', models.DateTimeField()),
                ('DataChange_LastModifiedBy', models.CharField(max_length=32, null=True)),
                ('DataChange_LastTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
